/* ===== 数据文件：词汇、题库、评估题 ===== */

// ============ 四级高频词汇（精选200个） ============
const cet4Words = [
    {en: "abandon", cn: "v. 放弃；抛弃", phonetic: "/əˈbændən/", example: "He abandoned his car in the snow."},
    {en: "ability", cn: "n. 能力；才能", phonetic: "/əˈbɪləti/", example: "She has the ability to solve problems."},
    {en: "absolute", cn: "adj. 绝对的；完全的", phonetic: "/ˈæbsəluːt/", example: "I have absolute trust in her."},
    {en: "absorb", cn: "v. 吸收；吸引", phonetic: "/əbˈzɔːb/", example: "Plants absorb sunlight."},
    {en: "abstract", cn: "adj. 抽象的 n. 摘要", phonetic: "/ˈæbstrækt/", example: "Abstract art is hard to understand."},
    {en: "academic", cn: "adj. 学术的；学院的", phonetic: "/ˌækəˈdemɪk/", example: "He has an academic background."},
    {en: "accept", cn: "v. 接受；同意", phonetic: "/əkˈsept/", example: "I accept your apology."},
    {en: "access", cn: "n. 通道；使用权 v. 访问", phonetic: "/ˈækses/", example: "Students have access to the library."},
    {en: "accident", cn: "n. 事故；意外", phonetic: "/ˈæksɪdənt/", example: "He was injured in a car accident."},
    {en: "accompany", cn: "v. 陪伴；伴随", phonetic: "/əˈkʌmpəni/", example: "She accompanied me to the doctor."},
    {en: "accomplish", cn: "v. 完成；实现", phonetic: "/əˈkʌmplɪʃ/", example: "We accomplished our goal."},
    {en: "accurate", cn: "adj. 准确的；精确的", phonetic: "/ˈækjərət/", example: "The report is accurate."},
    {en: "achieve", cn: "v. 达到；完成", phonetic: "/əˈtʃiːv/", example: "She achieved success through hard work."},
    {en: "acquire", cn: "v. 获得；学到", phonetic: "/əˈkwaɪə(r)/", example: "He acquired a new skill."},
    {en: "adapt", cn: "v. 适应；改编", phonetic: "/əˈdæpt/", example: "Children adapt quickly to new environments."},
    {en: "adequate", cn: "adj. 足够的；适当的", phonetic: "/ˈædɪkwət/", example: "The food is adequate for everyone."},
    {en: "adjust", cn: "v. 调整；适应", phonetic: "/əˈdʒʌst/", example: "Please adjust the volume."},
    {en: "admire", cn: "v. 钦佩；欣赏", phonetic: "/ədˈmaɪə(r)/", example: "I admire her courage."},
    {en: "admit", cn: "v. 承认；准许进入", phonetic: "/ədˈmɪt/", example: "He admitted his mistake."},
    {en: "adopt", cn: "v. 采用；收养", phonetic: "/əˈdɒpt/", example: "They adopted a new method."},
    {en: "advance", cn: "v./n. 前进；进步", phonetic: "/ədˈvɑːns/", example: "Technology advances rapidly."},
    {en: "advantage", cn: "n. 优势；有利条件", phonetic: "/ədˈvɑːntɪdʒ/", example: "Speaking English is an advantage."},
    {en: "adventure", cn: "n. 冒险；奇遇", phonetic: "/ədˈventʃə(r)/", example: "They went on an adventure."},
    {en: "advertise", cn: "v. 做广告；宣传", phonetic: "/ˈædvətaɪz/", example: "They advertise on TV."},
    {en: "advise", cn: "v. 建议；劝告", phonetic: "/ədˈvaɪz/", example: "I advise you to study harder."},
    {en: "affect", cn: "v. 影响；感动", phonetic: "/əˈfekt/", example: "The weather affects my mood."},
    {en: "afford", cn: "v. 买得起；承担得起", phonetic: "/əˈfɔːd/", example: "I can't afford a new car."},
    {en: "agriculture", cn: "n. 农业；农学", phonetic: "/ˈæɡrɪkʌltʃə(r)/", example: "Agriculture is important to the economy."},
    {en: "ancient", cn: "adj. 古代的；古老的", phonetic: "/ˈeɪnʃənt/", example: "They visited ancient ruins."},
    {en: "announce", cn: "v. 宣布；通告", phonetic: "/əˈnaʊns/", example: "They announced the winner."},
    {en: "annual", cn: "adj. 每年的 n. 年刊", phonetic: "/ˈænjuəl/", example: "We have an annual meeting."},
    {en: "anxious", cn: "adj. 焦虑的；渴望的", phonetic: "/ˈæŋkʃəs/", example: "She felt anxious about the exam."},
    {en: "apologize", cn: "v. 道歉", phonetic: "/əˈpɒlədʒaɪz/", example: "I apologize for being late."},
    {en: "appeal", cn: "v./n. 呼吁；吸引", phonetic: "/əˈpiːl/", example: "The idea appeals to me."},
    {en: "appear", cn: "v. 出现；似乎", phonetic: "/əˈpɪə(r)/", example: "He appeared tired."},
    {en: "application", cn: "n. 申请；应用", phonetic: "/ˌæplɪˈkeɪʃn/", example: "I submitted my application."},
    {en: "appreciate", cn: "v. 欣赏；感激", phonetic: "/əˈpriːʃieɪt/", example: "I appreciate your help."},
    {en: "approach", cn: "v. 接近 n. 方法", phonetic: "/əˈprəʊtʃ/", example: "We need a new approach."},
    {en: "appropriate", cn: "adj. 适当的", phonetic: "/əˈprəʊpriət/", example: "Choose the appropriate answer."},
    {en: "approve", cn: "v. 赞成；批准", phonetic: "/əˈpruːv/", example: "My parents approve of my decision."},
    {en: "argue", cn: "v. 争论；辩论", phonetic: "/ˈɑːɡjuː/", example: "They argued about politics."},
    {en: "arrange", cn: "v. 安排；整理", phonetic: "/əˈreɪndʒ/", example: "I arranged the meeting."},
    {en: "arrest", cn: "v./n. 逮捕", phonetic: "/əˈrest/", example: "The police arrested the thief."},
    {en: "arrive", cn: "v. 到达；达成", phonetic: "/əˈraɪv/", example: "We arrived at the station."},
    {en: "article", cn: "n. 文章；物品", phonetic: "/ˈɑːtɪkl/", example: "I read an interesting article."},
    {en: "artificial", cn: "adj. 人工的；人造的", phonetic: "/ˌɑːtɪˈfɪʃl/", example: "Artificial intelligence is growing."},
    {en: "aspect", cn: "n. 方面；外观", phonetic: "/ˈæspekt/", example: "Consider every aspect of the problem."},
    {en: "assemble", cn: "v. 集合；组装", phonetic: "/əˈsembl/", example: "They assembled the furniture."},
    {en: "assess", cn: "v. 评估；评定", phonetic: "/əˈses/", example: "We need to assess the damage."},
    {en: "assign", cn: "v. 分配；指派", phonetic: "/əˈsaɪn/", example: "The teacher assigned homework."},
    {en: "assist", cn: "v. 援助；帮助", phonetic: "/əˈsɪst/", example: "Can I assist you?"},
    {en: "associate", cn: "v. 联系 n. 同事", phonetic: "/əˈsəʊsieɪt/", example: "I associate summer with beaches."},
    {en: "assume", cn: "v. 假定；承担", phonetic: "/əˈsjuːm/", example: "I assume you are right."},
    {en: "assure", cn: "v. 保证；使确信", phonetic: "/əˈʃʊə(r)/", example: "I assure you it's safe."},
    {en: "atmosphere", cn: "n. 气氛；大气", phonetic: "/ˈætməsfɪə(r)/", example: "The atmosphere was tense."},
    {en: "attach", cn: "v. 附加；连接", phonetic: "/əˈtætʃ/", example: "Please attach the file."},
    {en: "attempt", cn: "v./n. 尝试；企图", phonetic: "/əˈtempt/", example: "He attempted to escape."},
    {en: "attend", cn: "v. 出席；参加", phonetic: "/əˈtend/", example: "She attended the conference."},
    {en: "attention", cn: "n. 注意；关心", phonetic: "/əˈtenʃn/", example: "Pay attention to the teacher."},
    {en: "attitude", cn: "n. 态度；看法", phonetic: "/ˈætɪtjuːd/", example: "He has a positive attitude."},
    {en: "attract", cn: "v. 吸引；引起", phonetic: "/əˈtrækt/", example: "The show attracted many viewers."},
    {en: "audience", cn: "n. 观众；听众", phonetic: "/ˈɔːdiəns/", example: "The audience applauded."},
    {en: "authority", cn: "n. 权威；当局", phonetic: "/ɔːˈθɒrəti/", example: "He has authority over the team."},
    {en: "available", cn: "adj. 可用的；可得到的", phonetic: "/əˈveɪləbl/", example: "Tickets are available online."},
    {en: "average", cn: "adj./n. 平均的", phonetic: "/ˈævərɪdʒ/", example: "The average temperature is 25°C."},
    {en: "avoid", cn: "v. 避免；避开", phonetic: "/əˈvɔɪd/", example: "Try to avoid stress."},
    {en: "aware", cn: "adj. 意识到的；知道的", phonetic: "/əˈweə(r)/", example: "Are you aware of the risk?"},
    {en: "balance", cn: "n./v. 平衡", phonetic: "/ˈbæləns/", example: "Work-life balance is important."},
    {en: "barrier", cn: "n. 障碍；屏障", phonetic: "/ˈbæriə(r)/", example: "Language is a barrier."},
    {en: "behave", cn: "v. 表现；行为", phonetic: "/bɪˈheɪv/", example: "The children behaved well."},
    {en: "benefit", cn: "n./v. 利益；受益", phonetic: "/ˈbenɪfɪt/", example: "Exercise benefits your health."},
    {en: "beyond", cn: "prep. 超过；在...那边", phonetic: "/bɪˈjɒnd/", example: "It's beyond my expectations."},
    {en: "birth", cn: "n. 出生；诞生", phonetic: "/bɜːθ/", example: "She gave birth to a baby."},
    {en: "blame", cn: "v./n. 责备；责任", phonetic: "/bleɪm/", example: "Don't blame yourself."},
    {en: "borrow", cn: "v. 借；借用", phonetic: "/ˈbɒrəʊ/", example: "Can I borrow your pen?"},
    {en: "brief", cn: "adj. 简短的 n. 摘要", phonetic: "/briːf/", example: "Please be brief."},
    {en: "brilliant", cn: "adj. 杰出的；明亮的", phonetic: "/ˈbrɪliənt/", example: "She is a brilliant student."},
    {en: "budget", cn: "n. 预算 v. 编制预算", phonetic: "/ˈbʌdʒɪt/", example: "We need a budget plan."},
    {en: "calculate", cn: "v. 计算；估计", phonetic: "/ˈkælkjuleɪt/", example: "Calculate the total cost."},
    {en: "campaign", cn: "n. 运动；战役", phonetic: "/kæmˈpeɪn/", example: "They launched a campaign."},
    {en: "candidate", cn: "n. 候选人；应试者", phonetic: "/ˈkændɪdət/", example: "He is a candidate for president."},
    {en: "capable", cn: "adj. 有能力的；能干的", phonetic: "/ˈkeɪpəbl/", example: "She is capable of doing it."},
    {en: "capacity", cn: "n. 容量；能力", phonetic: "/kəˈpæsəti/", example: "The stadium has a large capacity."},
    {en: "capture", cn: "v. 捕获；夺取", phonetic: "/ˈkæptʃə(r)/", example: "The photo captured the moment."},
    {en: "career", cn: "n. 职业；生涯", phonetic: "/kəˈrɪə(r)/", example: "She has a successful career."},
    {en: "carry", cn: "v. 携带；搬运", phonetic: "/ˈkæri/", example: "Please carry this bag."},
    {en: "category", cn: "n. 种类；类别", phonetic: "/ˈkætəɡəri/", example: "Books fall into categories."},
    {en: "cause", cn: "n. 原因 v. 引起", phonetic: "/kɔːz/", example: "What caused the accident?"},
    {en: "cease", cn: "v. 停止；终止", phonetic: "/siːs/", example: "The rain ceased."},
    {en: "celebrate", cn: "v. 庆祝；赞美", phonetic: "/ˈselɪbreɪt/", example: "We celebrated his birthday."},
    {en: "challenge", cn: "n./v. 挑战", phonetic: "/ˈtʃælɪndʒ/", example: "I accept the challenge."},
    {en: "character", cn: "n. 性格；角色；字符", phonetic: "/ˈkærəktə(r)/", example: "He has a strong character."},
    {en: "charge", cn: "v. 收费；指控 n. 费用", phonetic: "/tʃɑːdʒ/", example: "They charge $10 for entry."},
    {en: "cheap", cn: "adj. 便宜的；廉价的", phonetic: "/tʃiːp/", example: "This shirt is cheap."},
    {en: "cheat", cn: "v. 欺骗；作弊", phonetic: "/tʃiːt/", example: "He cheated on the exam."},
    {en: "check", cn: "v. 检查；核对", phonetic: "/tʃek/", example: "Please check your answers."},
    {en: "cheer", cn: "v. 欢呼；使高兴", phonetic: "/tʃɪə(r)/", example: "The crowd cheered."},
    {en: "choose", cn: "v. 选择；挑选", phonetic: "/tʃuːz/", example: "Choose wisely."},
    {en: "circle", cn: "n. 圆圈 v. 环绕", phonetic: "/ˈsɜːkl/", example: "Draw a circle."},
    {en: "circumstance", cn: "n. 情况；环境", phonetic: "/ˈsɜːkəmstəns/", example: "Under no circumstances should you lie."},
    {en: "claim", cn: "v. 声称；要求", phonetic: "/kleɪm/", example: "He claimed to be innocent."},
    {en: "clarify", cn: "v. 澄清；阐明", phonetic: "/ˈklærəfaɪ/", example: "Can you clarify your point?"},
    {en: "classic", cn: "adj. 经典的 n. 经典作品", phonetic: "/ˈklæsɪk/", example: "This is a classic novel."},
    {en: "climate", cn: "n. 气候；风气", phonetic: "/ˈklaɪmət/", example: "The climate here is mild."},
    {en: "combine", cn: "v. 结合；联合", phonetic: "/kəmˈbaɪn/", example: "Combine the ingredients."},
    {en: "comfort", cn: "n./v. 舒适；安慰", phonetic: "/ˈkʌmfət/", example: "This chair is comfortable."},
    {en: "command", cn: "n./v. 命令；指挥", phonetic: "/kəˈmɑːnd/", example: "He gave a command."},
    {en: "comment", cn: "n./v. 评论；意见", phonetic: "/ˈkɒment/", example: "Do you have any comments?"},
    {en: "commercial", cn: "adj. 商业的 n. 广告", phonetic: "/kəˈmɜːʃl/", example: "It's a commercial success."},
    {en: "commit", cn: "v. 承诺；犯(罪)", phonetic: "/kəˈmɪt/", example: "He committed a crime."},
    {en: "common", cn: "adj. 普通的；共同的", phonetic: "/ˈkɒmən/", example: "It's a common mistake."},
    {en: "communicate", cn: "v. 交流；沟通", phonetic: "/kəˈmjuːnɪkeɪt/", example: "We communicate by email."},
    {en: "community", cn: "n. 社区；团体", phonetic: "/kəˈmjuːnəti/", example: "The community is friendly."},
    {en: "compare", cn: "v. 比较；对比", phonetic: "/kəmˈpeə(r)/", example: "Compare the two options."},
    {en: "compete", cn: "v. 竞争；比赛", phonetic: "/kəmˈpiːt/", example: "They compete in sports."},
    {en: "complain", cn: "v. 抱怨；投诉", phonetic: "/kəmˈpleɪn/", example: "He complained about the food."},
    {en: "complete", cn: "adj. 完整的 v. 完成", phonetic: "/kəmˈpliːt/", example: "Complete the form."},
    {en: "complex", cn: "adj. 复杂的 n. 综合体", phonetic: "/ˈkɒmpleks/", example: "This is a complex problem."},
    {en: "concept", cn: "n. 概念；观念", phonetic: "/ˈkɒnsept/", example: "Explain the concept."},
    {en: "conclude", cn: "v. 得出结论；结束", phonetic: "/kənˈkluːd/", example: "We concluded the meeting."},
    {en: "condition", cn: "n. 条件；状况", phonetic: "/kənˈdɪʃn/", example: "The car is in good condition."},
    {en: "conduct", cn: "v. 进行；指挥 n. 行为", phonetic: "/kənˈdʌkt/", example: "Conduct an experiment."},
    {en: "confident", cn: "adj. 自信的；确信的", phonetic: "/ˈkɒnfɪdənt/", example: "She is confident in her ability."},
    {en: "confirm", cn: "v. 确认；证实", phonetic: "/kənˈfɜːm/", example: "Please confirm your booking."},
    {en: "conflict", cn: "n./v. 冲突；矛盾", phonetic: "/ˈkɒnflɪkt/", example: "There is a conflict of interest."},
    {en: "confuse", cn: "v. 使困惑；混淆", phonetic: "/kənˈfjuːz/", example: "Don't confuse the two words."},
    {en: "connect", cn: "v. 连接；联系", phonetic: "/kəˈnekt/", example: "Connect the wires."},
    {en: "conscious", cn: "adj. 有意识的；意识到的", phonetic: "/ˈkɒnʃəs/", example: "He is conscious of his mistake."},
    {en: "consider", cn: "v. 考虑；认为", phonetic: "/kənˈsɪdə(r)/", example: "Consider your options."},
    {en: "consist", cn: "v. 由...组成", phonetic: "/kənˈsɪst/", example: "The team consists of 10 people."},
    {en: "constant", cn: "adj. 不断的；恒定的", phonetic: "/ˈkɒnstənt/", example: "There is constant noise."},
    {en: "consume", cn: "v. 消费；消耗", phonetic: "/kənˈsjuːm/", example: "We consume a lot of energy."},
    {en: "contact", cn: "n./v. 联系；接触", phonetic: "/ˈkɒntækt/", example: "I'll contact you later."},
    {en: "contain", cn: "v. 包含；容纳", phonetic: "/kənˈteɪn/", example: "The box contains books."},
    {en: "contemporary", cn: "adj. 当代的；同时代的", phonetic: "/kənˈtemprəri/", example: "Contemporary art is diverse."},
    {en: "content", cn: "n. 内容 adj. 满足的", phonetic: "/ˈkɒntent/", example: "The content is interesting."},
    {en: "contest", cn: "n. 比赛；竞赛", phonetic: "/ˈkɒntest/", example: "She won the contest."},
    {en: "context", cn: "n. 上下文；背景", phonetic: "/ˈkɒntekst/", example: "Consider the context."},
    {en: "continue", cn: "v. 继续；持续", phonetic: "/kənˈtɪnjuː/", example: "Please continue your work."},
    {en: "contract", cn: "n. 合同 v. 收缩", phonetic: "/ˈkɒntrækt/", example: "Sign the contract."},
    {en: "contrast", cn: "n./v. 对比；对照", phonetic: "/ˈkɒntrɑːst/", example: "There is a stark contrast."},
    {en: "contribute", cn: "v. 贡献；捐献", phonetic: "/kənˈtrɪbjuːt/", example: "Everyone should contribute."},
    {en: "convenient", cn: "adj. 方便的；便利的", phonetic: "/kənˈviːniənt/", example: "It's convenient to live here."},
    {en: "convince", cn: "v. 说服；使信服", phonetic: "/kənˈvɪns/", example: "He convinced me to go."},
    {en: "cooperate", cn: "v. 合作；协作", phonetic: "/kəʊˈɒpəreɪt/", example: "We should cooperate."},
    {en: "correct", cn: "adj. 正确的 v. 纠正", phonetic: "/kəˈrekt/", example: "Is this answer correct?"},
    {en: "cost", cn: "n. 成本 v. 花费", phonetic: "/kɒst/", example: "How much does it cost?"},
    {en: "council", cn: "n. 委员会；议会", phonetic: "/ˈkaʊnsl/", example: "The city council met."},
    {en: "count", cn: "v. 数；计算", phonetic: "/kaʊnt/", example: "Count the money."},
    {en: "courage", cn: "n. 勇气；胆量", phonetic: "/ˈkʌrɪdʒ/", example: "It takes courage to speak up."},
    {en: "create", cn: "v. 创造；创作", phonetic: "/kriˈeɪt/", example: "She created a masterpiece."},
    {en: "credit", cn: "n. 信用；学分；赞扬", phonetic: "/ˈkredɪt/", example: "He deserves credit for this."},
    {en: "crisis", cn: "n. 危机；紧急关头", phonetic: "/ˈkraɪsɪs/", example: "The country is in crisis."},
    {en: "criticize", cn: "v. 批评；评论", phonetic: "/ˈkrɪtɪsaɪz/", example: "Don't criticize others."},
    {en: "crowd", cn: "n. 人群 v. 拥挤", phonetic: "/kraʊd/", example: "A crowd gathered."},
    {en: "crucial", cn: "adj. 至关重要的", phonetic: "/ˈkruːʃl/", example: "This is a crucial decision."},
    {en: "culture", cn: "n. 文化；文明", phonetic: "/ˈkʌltʃə(r)/", example: "Chinese culture is rich."},
    {en: "current", cn: "adj. 当前的 n. 水流", phonetic: "/ˈkʌrənt/", example: "Current events are important."},
    {en: "damage", cn: "n./v. 损害；损坏", phonetic: "/ˈdæmɪdʒ/", example: "The storm caused damage."},
    {en: "debate", cn: "n./v. 辩论；讨论", phonetic: "/dɪˈbeɪt/", example: "They debated the issue."},
    {en: "decade", cn: "n. 十年", phonetic: "/ˈdekeɪd/", example: "He worked here for a decade."},
    {en: "decide", cn: "v. 决定；下决心", phonetic: "/dɪˈsaɪd/", example: "Decide what you want."},
    {en: "declare", cn: "v. 宣布；声明", phonetic: "/dɪˈkleə(r)/", example: "They declared independence."},
    {en: "decline", cn: "v. 下降；拒绝", phonetic: "/dɪˈklaɪn/", example: "Sales declined this year."},
    {en: "decrease", cn: "v./n. 减少；降低", phonetic: "/dɪˈkriːs/", example: "Prices have decreased."},
    {en: "dedicate", cn: "v. 致力于；献身", phonetic: "/ˈdedɪkeɪt/", example: "She dedicated herself to teaching."},
    {en: "defeat", cn: "v./n. 击败；战胜", phonetic: "/dɪˈfiːt/", example: "They defeated the enemy."},
    {en: "defend", cn: "v. 防御；辩护", phonetic: "/dɪˈfend/", example: "He defended his thesis."},
    {en: "define", cn: "v. 定义；解释", phonetic: "/dɪˈfaɪn/", example: "Define the term."},
    {en: "deliver", cn: "v. 递送；发表", phonetic: "/dɪˈlɪvə(r)/", example: "The package was delivered."},
    {en: "demand", cn: "n./v. 要求；需求", phonetic: "/dɪˈmɑːnd/", example: "There is high demand."},
    {en: "demonstrate", cn: "v. 证明；演示", phonetic: "/ˈdemənstreɪt/", example: "Let me demonstrate how it works."},
    {en: "deny", cn: "v. 否认；拒绝", phonetic: "/dɪˈnaɪ/", example: "He denied the accusation."},
    {en: "depend", cn: "v. 依靠；取决于", phonetic: "/dɪˈpend/", example: "It depends on the weather."},
    {en: "describe", cn: "v. 描述；形容", phonetic: "/dɪˈskraɪb/", example: "Describe the scene."},
    {en: "deserve", cn: "v. 值得；应得", phonetic: "/dɪˈzɜːv/", example: "You deserve a break."},
    {en: "design", cn: "v./n. 设计", phonetic: "/dɪˈzaɪn/", example: "She designs clothes."},
    {en: "despite", cn: "prep. 尽管；不管", phonetic: "/dɪˈspaɪt/", example: "Despite the rain, we went out."},
    {en: "destroy", cn: "v. 破坏；毁灭", phonetic: "/dɪˈstrɔɪ/", example: "The fire destroyed the house."},
    {en: "detail", cn: "n. 细节；详情", phonetic: "/ˈdiːteɪl/", example: "Explain in detail."},
    {en: "determine", cn: "v. 决定；确定", phonetic: "/dɪˈtɜːmɪn/", example: "We need to determine the cause."},
    {en: "develop", cn: "v. 发展；开发", phonetic: "/dɪˈveləp/", example: "Children develop quickly."},
    {en: "devote", cn: "v. 献身；专心于", phonetic: "/dɪˈvəʊt/", example: "She devoted herself to science."},
    {en: "differ", cn: "v. 不同；相异", phonetic: "/ˈdɪfə(r)/", example: "Opinions differ."},
    {en: "difficult", cn: "adj. 困难的；艰难的", phonetic: "/ˈdɪfɪkəlt/", example: "This is a difficult task."},
    {en: "direct", cn: "adj. 直接的 v. 指挥", phonetic: "/dəˈrekt/", example: "Take a direct route."},
    {en: "disappear", cn: "v. 消失；失踪", phonetic: "/ˌdɪsəˈpɪə(r)/", example: "The sun disappeared behind clouds."},
    {en: "disaster", cn: "n. 灾难；灾祸", phonetic: "/dɪˈzɑːstə(r)/", example: "The earthquake was a disaster."},
    {en: "discover", cn: "v. 发现；找到", phonetic: "/dɪˈskʌvə(r)/", example: "Columbus discovered America."},
    {en: "discuss", cn: "v. 讨论；商议", phonetic: "/dɪˈskʌs/", example: "Let's discuss the plan."},
    {en: "display", cn: "v./n. 显示；陈列", phonetic: "/dɪˈspleɪ/", example: "The museum displays art."},
    {en: "distance", cn: "n. 距离；远方", phonetic: "/ˈdɪstəns/", example: "What's the distance?"},
    {en: "distribute", cn: "v. 分配；分发", phonetic: "/dɪˈstrɪbjuːt/", example: "Distribute the papers."},
    {en: "divide", cn: "v. 分开；除", phonetic: "/dɪˈvaɪd/", example: "Divide the cake."},
    {en: "doubt", cn: "n./v. 怀疑", phonetic: "/daʊt/", example: "I have no doubt."},
    {en: "dramatic", cn: "adj. 戏剧性的；引人注目的", phonetic: "/drəˈmætɪk/", example: "There was a dramatic change."},
    {en: "draw", cn: "v. 画；吸引；拉", phonetic: "/drɔː/", example: "She drew a picture."},
    {en: "drink", cn: "v. 喝 n. 饮料", phonetic: "/drɪŋk/", example: "Would you like a drink?"},
    {en: "drive", cn: "v. 驾驶；驱动", phonetic: "/draɪv/", example: "He drives a car."},
    {en: "drop", cn: "v. 落下；下降", phonetic: "/drɒp/", example: "He dropped his keys."},
    {en: "economy", cn: "n. 经济；节约", phonetic: "/ɪˈkɒnəmi/", example: "The economy is growing."},
    {en: "educate", cn: "v. 教育；培养", phonetic: "/ˈedʒukeɪt/", example: "Schools educate children."},
    {en: "effect", cn: "n. 影响；效果", phonetic: "/ɪˈfekt/", example: "The medicine took effect."},
    {en: "effort", cn: "n. 努力；尽力", phonetic: "/ˈefət/", example: "Make an effort."},
    {en: "emerge", cn: "v. 出现；浮现", phonetic: "/ɪˈmɜːdʒ/", example: "New problems emerged."},
    {en: "emotion", cn: "n. 情感；情绪", phonetic: "/ɪˈməʊʃn/", example: "She showed no emotion."},
    {en: "emphasize", cn: "v. 强调；着重", phonetic: "/ˈemfəsaɪz/", example: "He emphasized the importance."},
    {en: "employ", cn: "v. 雇用；使用", phonetic: "/ɪmˈplɔɪ/", example: "They employ 50 workers."},
    {en: "enable", cn: "v. 使能够；使成为可能", phonetic: "/ɪˈneɪbl/", example: "This enables us to work faster."},
    {en: "encourage", cn: "v. 鼓励；激励", phonetic: "/ɪnˈkʌrɪdʒ/", example: "Parents should encourage kids."},
    {en: "energy", cn: "n. 能量；精力", phonetic: "/ˈenədʒi/", example: "I have no energy today."},
    {en: "engage", cn: "v. 从事；参与", phonetic: "/ɪnˈɡeɪdʒ/", example: "He engaged in research."},
    {en: "enhance", cn: "v. 提高；增强", phonetic: "/ɪnˈhɑːns/", example: "This enhances performance."},
    {en: "enjoy", cn: "v. 享受；喜欢", phonetic: "/ɪnˈdʒɔɪ/", example: "I enjoy reading."},
    {en: "ensure", cn: "v. 确保；保证", phonetic: "/ɪnˈʃʊə(r)/", example: "Ensure your safety."},
    {en: "enter", cn: "v. 进入；加入", phonetic: "/ˈentə(r)/", example: "Enter the room."},
    {en: "entire", cn: "adj. 整个的；全部的", phonetic: "/ɪnˈtaɪə(r)/", example: "The entire class passed."},
    {en: "environment", cn: "n. 环境；周围状况", phonetic: "/ɪnˈvaɪrənmənt/", example: "Protect the environment."},
    {en: "equal", cn: "adj. 平等的 v. 等于", phonetic: "/ˈiːkwəl/", example: "Two plus two equals four."},
    {en: "equip", cn: "v. 装备；配备", phonetic: "/ɪˈkwɪp/", example: "The lab is well equipped."},
    {en: "error", cn: "n. 错误；误差", phonetic: "/ˈerə(r)/", example: "There was an error."},
    {en: "escape", cn: "v./n. 逃跑；逃脱", phonetic: "/ɪˈskeɪp/", example: "The prisoner escaped."},
    {en: "establish", cn: "v. 建立；创立", phonetic: "/ɪˈstæblɪʃ/", example: "They established a company."},
    {en: "estimate", cn: "v./n. 估计；评价", phonetic: "/ˈestɪmeɪt/", example: "Estimate the cost."},
    {en: "evaluate", cn: "v. 评估；评价", phonetic: "/ɪˈvæljueɪt/", example: "Evaluate the results."},
    {en: "evidence", cn: "n. 证据；迹象", phonetic: "/ˈevɪdəns/", example: "There is no evidence."},
    {en: "evolve", cn: "v. 进化；演变", phonetic: "/ɪˈvɒlv/", example: "Species evolve over time."},
    {en: "exact", cn: "adj. 精确的；确切的", phonetic: "/ɪɡˈzækt/", example: "What's the exact time?"},
    {en: "examine", cn: "v. 检查；考试", phonetic: "/ɪɡˈzæmɪn/", example: "The doctor examined him."},
    {en: "example", cn: "n. 例子；榜样", phonetic: "/ɪɡˈzɑːmpl/", example: "Give me an example."},
    {en: "exceed", cn: "v. 超过；超出", phonetic: "/ɪkˈsiːd/", example: "Don't exceed the speed limit."},
    {en: "exchange", cn: "v./n. 交换；交流", phonetic: "/ɪksˈtʃeɪndʒ/", example: "We exchanged gifts."},
    {en: "excite", cn: "v. 使兴奋；激发", phonetic: "/ɪkˈsaɪt/", example: "The news excited everyone."},
    {en: "exclude", cn: "v. 排除；不包括", phonetic: "/ɪkˈskluːd/", example: "Please exclude me from the list."},
    {en: "exercise", cn: "n./v. 锻炼；练习", phonetic: "/ˈeksəsaɪz/", example: "Exercise regularly."},
    {en: "expand", cn: "v. 扩大；膨胀", phonetic: "/ɪkˈspænd/", example: "The company expanded."},
    {en: "expect", cn: "v. 期待；预期", phonetic: "/ɪkˈspekt/", example: "I expect good results."},
    {en: "experience", cn: "n./v. 经验；经历", phonetic: "/ɪkˈspɪəriəns/", example: "She has experience in teaching."},
    {en: "experiment", cn: "n. 实验；试验", phonetic: "/ɪkˈsperɪmənt/", example: "Do the experiment."},
    {en: "explain", cn: "v. 解释；说明", phonetic: "/ɪkˈspleɪn/", example: "Can you explain this?"},
    {en: "explore", cn: "v. 探索；探险", phonetic: "/ɪkˈsplɔː(r)/", example: "Explore the new city."},
    {en: "express", cn: "v. 表达 adj. 快速的", phonetic: "/ɪkˈspres/", example: "Express your opinion."},
    {en: "extend", cn: "v. 延伸；扩大", phonetic: "/ɪkˈstend/", example: "Extend the deadline."},
    {en: "extra", cn: "adj. 额外的", phonetic: "/ˈekstrə/", example: "I need extra time."}
];

// ============ 六级高频词汇（精选150个） ============
const cet6Words = [
    {en: "abnormal", cn: "adj. 反常的；变态的", phonetic: "/æbˈnɔːml/", example: "His behavior was abnormal."},
    {en: "abolish", cn: "v. 废除；废止", phonetic: "/əˈbɒlɪʃ/", example: "They abolished the old law."},
    {en: "abrupt", cn: "adj. 突然的；唐突的", phonetic: "/əˈbrʌpt/", example: "The meeting ended abruptly."},
    {en: "absurd", cn: "adj. 荒谬的；可笑的", phonetic: "/əbˈsɜːd/", example: "What an absurd idea!"},
    {en: "accelerate", cn: "v. 加速；促进", phonetic: "/əkˈseləreɪt/", example: "The car accelerated."},
    {en: "accommodate", cn: "v. 容纳；适应", phonetic: "/əˈkɒmədeɪt/", example: "The hotel accommodates 200 guests."},
    {en: "accumulate", cn: "v. 积累；积聚", phonetic: "/əˈkjuːmjəleɪt/", example: "He accumulated wealth."},
    {en: "acknowledge", cn: "v. 承认；致谢", phonetic: "/əkˈnɒlɪdʒ/", example: "He acknowledged his mistake."},
    {en: "acquaint", cn: "v. 使熟悉；使认识", phonetic: "/əˈkweɪnt/", example: "Let me acquaint you with the rules."},
    {en: "adhere", cn: "v. 坚持；黏附", phonetic: "/ədˈhɪə(r)/", example: "Adhere to the rules."},
    {en: "advocate", cn: "v. 提倡 n. 拥护者", phonetic: "/ˈædvəkeɪt/", example: "She advocates human rights."},
    {en: "aesthetic", cn: "adj. 美学的；审美的", phonetic: "/iːsˈθetɪk/", example: "The design has aesthetic appeal."},
    {en: "affiliate", cn: "v. 使隶属 n. 附属机构", phonetic: "/əˈfɪlieɪt/", example: "The company is affiliated with a larger firm."},
    {en: "aggravate", cn: "v. 加重；恶化", phonetic: "/ˈæɡrəveɪt/", example: "Don't aggravate the situation."},
    {en: "alleviate", cn: "v. 减轻；缓解", phonetic: "/əˈliːvieɪt/", example: "This medicine alleviates pain."},
    {en: "allocate", cn: "v. 分配；分派", phonetic: "/ˈæləkeɪt/", example: "Allocate the budget wisely."},
    {en: "ambiguous", cn: "adj. 模糊的；模棱两可的", phonetic: "/æmˈbɪɡjuəs/", example: "His answer was ambiguous."},
    {en: "ambitious", cn: "adj. 有雄心的；野心勃勃的", phonetic: "/æmˈbɪʃəs/", example: "She is an ambitious person."},
    {en: "analogy", cn: "n. 类比；相似", phonetic: "/əˈnælədʒi/", example: "Draw an analogy between the two."},
    {en: "anonymous", cn: "adj. 匿名的；无名的", phonetic: "/əˈnɒnɪməs/", example: "An anonymous donor gave the money."},
    {en: "apparatus", cn: "n. 器械；装置", phonetic: "/ˌæpəˈreɪtəs/", example: "The laboratory has modern apparatus."},
    {en: "apparent", cn: "adj. 明显的；表面的", phonetic: "/əˈpærənt/", example: "It's apparent that he's lying."},
    {en: "appliance", cn: "n. 器具；器械", phonetic: "/əˈplaɪəns/", example: "Kitchen appliances are useful."},
    {en: "appreciable", cn: "adj. 可察觉的；相当可观的", phonetic: "/əˈpriːʃəbl/", example: "There's an appreciable difference."},
    {en: "arbitrary", cn: "adj. 任意的；武断的", phonetic: "/ˈɑːbɪtrəri/", example: "The decision seemed arbitrary."},
    {en: "articulate", cn: "v. 清楚表达 adj. 口才好的", phonetic: "/ɑːˈtɪkjuleɪt/", example: "She can articulate her thoughts."},
    {en: "ascend", cn: "v. 上升；攀登", phonetic: "/əˈsend/", example: "We ascended the mountain."},
    {en: "ascribe", cn: "v. 归因于；归咎于", phonetic: "/əˈskraɪb/", example: "He ascribed his success to luck."},
    {en: "aspire", cn: "v. 渴望；追求", phonetic: "/əˈspaɪə(r)/", example: "She aspires to be a doctor."},
    {en: "assemble", cn: "v. 集合；装配", phonetic: "/əˈsembl/", example: "Assemble the parts carefully."},
    {en: "assert", cn: "v. 断言；主张", phonetic: "/əˈsɜːt/", example: "He asserted his innocence."},
    {en: "assess", cn: "v. 评估；估价", phonetic: "/əˈses/", example: "Assess the damage."},
    {en: "assume", cn: "v. 假定；承担", phonetic: "/əˈsjuːm/", example: "I assume you agree."},
    {en: "assurance", cn: "n. 保证；确信", phonetic: "/əˈʃʊərəns/", example: "He gave me his assurance."},
    {en: "attain", cn: "v. 达到；获得", phonetic: "/əˈteɪn/", example: "She attained her goal."},
    {en: "attribute", cn: "v. 归因于 n. 属性", phonetic: "/əˈtrɪbjuːt/", example: "Attribute the failure to bad luck."},
    {en: "authentic", cn: "adj. 真实的；可靠的", phonetic: "/ɔːˈθentɪk/", example: "This is an authentic painting."},
    {en: "autonomous", cn: "adj. 自治的；自主的", phonetic: "/ɔːˈtɒnəməs/", example: "The region is autonomous."},
    {en: "beneficial", cn: "adj. 有益的；有利的", phonetic: "/ˌbenɪˈfɪʃl/", example: "Exercise is beneficial to health."},
    {en: "bewilder", cn: "v. 使迷惑；使不知所措", phonetic: "/bɪˈwɪldə(r)/", example: "The instructions bewildered me."},
    {en: "bizarre", cn: "adj. 奇异的；古怪的", phonetic: "/bɪˈzɑː(r)/", example: "He told a bizarre story."},
    {en: "boost", cn: "v./n. 促进；提高", phonetic: "/buːst/", example: "This will boost sales."},
    {en: "breach", cn: "n./v. 违反；破坏", phonetic: "/briːtʃ/", example: "It's a breach of contract."},
    {en: "bureaucracy", cn: "n. 官僚主义；政府机构", phonetic: "/bjʊəˈrɒkrəsi/", example: "The bureaucracy is slow."},
    {en: "cater", cn: "v. 迎合；提供餐饮", phonetic: "/ˈkeɪtə(r)/", example: "The restaurant caters to tourists."},
    {en: "cease", cn: "v. 停止；终止", phonetic: "/siːs/", example: "The company ceased operations."},
    {en: "celebrity", cn: "n. 名人；名声", phonetic: "/səˈlebrəti/", example: "He became a celebrity overnight."},
    {en: "chronic", cn: "adj. 慢性的；长期的", phonetic: "/ˈkrɒnɪk/", example: "He has chronic back pain."},
    {en: "circulation", cn: "n. 循环；流通", phonetic: "/ˌsɜːkjəˈleɪʃn/", example: "Exercise improves blood circulation."},
    {en: "civilize", cn: "v. 使文明；教化", phonetic: "/ˈsɪvəlaɪz/", example: "Education civilizes people."},
    {en: "clarify", cn: "v. 澄清；阐明", phonetic: "/ˈklærəfaɪ/", example: "Clarify your position."},
    {en: "coincide", cn: "v. 同时发生；一致", phonetic: "/ˌkəʊɪnˈsaɪd/", example: "Our holidays coincide."},
    {en: "collaborate", cn: "v. 合作；协作", phonetic: "/kəˈlæbəreɪt/", example: "They collaborated on the project."},
    {en: "collide", cn: "v. 碰撞；冲突", phonetic: "/kəˈlaɪd/", example: "The cars collided."},
    {en: "commence", cn: "v. 开始；着手", phonetic: "/kəˈmens/", example: "The meeting will commence soon."},
    {en: "commodity", cn: "n. 商品；日用品", phonetic: "/kəˈmɒdəti/", example: "Oil is a valuable commodity."},
    {en: "commonplace", cn: "adj. 平凡的 n. 寻常事物", phonetic: "/ˈkɒmənpleɪs/", example: "Mobile phones are commonplace now."},
    {en: "compatible", cn: "adj. 兼容的；合得来的", phonetic: "/kəmˈpætəbl/", example: "The software is compatible with my PC."},
    {en: "compensate", cn: "v. 补偿；赔偿", phonetic: "/ˈkɒmpenseɪt/", example: "The company compensated the victims."},
    {en: "competent", cn: "adj. 有能力的；胜任的", phonetic: "/ˈkɒmpɪtənt/", example: "She is a competent teacher."},
    {en: "compile", cn: "v. 编辑；汇编", phonetic: "/kəmˈpaɪl/", example: "Compile a list of names."},
    {en: "complement", cn: "v./n. 补充；补足", phonetic: "/ˈkɒmplɪment/", example: "The wine complements the meal."},
    {en: "comprehensive", cn: "adj. 全面的；综合的", phonetic: "/ˌkɒmprɪˈhensɪv/", example: "We need a comprehensive plan."},
    {en: "comprise", cn: "v. 包含；由...组成", phonetic: "/kəmˈpraɪz/", example: "The committee comprises 10 members."},
    {en: "conceive", cn: "v. 构想；怀孕", phonetic: "/kənˈsiːv/", example: "He conceived a brilliant idea."},
    {en: "conception", cn: "n. 概念；构想", phonetic: "/kənˈsepʃn/", example: "The conception of the plan was brilliant."},
    {en: "concession", cn: "n. 让步；特许权", phonetic: "/kənˈseʃn/", example: "They made concessions to reach a deal."},
    {en: "concise", cn: "adj. 简洁的；简明的", phonetic: "/kənˈsaɪs/", example: "Give a concise answer."},
    {en: "condemn", cn: "v. 谴责；判刑", phonetic: "/kənˈdem/", example: "The public condemned the action."},
    {en: "conform", cn: "v. 遵守；符合", phonetic: "/kənˈfɔːm/", example: "Conform to the regulations."},
    {en: "confront", cn: "v. 面对；对抗", phonetic: "/kənˈfrʌnt/", example: "Confront your fears."},
    {en: "conscientious", cn: "adj. 认真的；尽责的", phonetic: "/ˌkɒnʃiˈenʃəs/", example: "She is a conscientious worker."},
    {en: "consecutive", cn: "adj. 连续的；连贯的", phonetic: "/kənˈsekjətɪv/", example: "It rained for three consecutive days."},
    {en: "consensus", cn: "n. 一致；共识", phonetic: "/kənˈsensəs/", example: "We reached a consensus."},
    {en: "conserve", cn: "v. 保存；保护", phonetic: "/kənˈsɜːv/", example: "Conserve water."},
    {en: "considerable", cn: "adj. 相当大的；重要的", phonetic: "/kənˈsɪdərəbl/", example: "He made a considerable amount of money."},
    {en: "consistent", cn: "adj. 一致的；始终如一的", phonetic: "/kənˈsɪstənt/", example: "His results are consistent."},
    {en: "consolidate", cn: "v. 巩固；合并", phonetic: "/kənˈsɒlɪdeɪt/", example: "Consolidate your knowledge."},
    {en: "conspicuous", cn: "adj. 显眼的；引人注目的", phonetic: "/kənˈspɪkjuəs/", example: "He was conspicuous by his absence."},
    {en: "constitute", cn: "v. 构成；组成", phonetic: "/ˈkɒnstɪtjuːt/", example: "Twelve months constitute a year."},
    {en: "constraint", cn: "n. 限制；约束", phonetic: "/kənˈstreɪnt/", example: "Financial constraints limit us."},
    {en: "consult", cn: "v. 咨询；查阅", phonetic: "/kənˈsʌlt/", example: "Consult a doctor."},
    {en: "consume", cn: "v. 消费；消耗", phonetic: "/kənˈsjuːm/", example: "We consume too much energy."},
    {en: "contemplate", cn: "v. 沉思；考虑", phonetic: "/ˈkɒntəmpleɪt/", example: "Contemplate your options."},
    {en: "contemporary", cn: "adj. 当代的 n. 同代人", phonetic: "/kənˈtemprəri/", example: "Contemporary artists are diverse."},
    {en: "contradict", cn: "v. 反驳；与...矛盾", phonetic: "/ˌkɒntrəˈdɪkt/", example: "Don't contradict yourself."},
    {en: "controversy", cn: "n. 争论；争议", phonetic: "/ˈkɒntrəvɜːsi/", example: "The decision caused controversy."},
    {en: "convey", cn: "v. 传达；运送", phonetic: "/kənˈveɪ/", example: "Convey my regards to her."},
    {en: "convict", cn: "v. 定罪 n. 囚犯", phonetic: "/kənˈvɪkt/", example: "He was convicted of theft."},
    {en: "cooperative", cn: "adj. 合作的 n. 合作社", phonetic: "/kəʊˈɒpərətɪv/", example: "She is cooperative at work."},
    {en: "correspond", cn: "v. 符合；通信", phonetic: "/ˌkɒrəˈspɒnd/", example: "The results correspond to our expectations."},
    {en: "corrupt", cn: "adj. 腐败的 v. 腐蚀", phonetic: "/kəˈrʌpt/", example: "The official was corrupt."},
    {en: "credible", cn: "adj. 可信的；可靠的", phonetic: "/ˈkredəbl/", example: "Is this a credible source?"},
    {en: "crucial", cn: "adj. 至关重要的", phonetic: "/ˈkruːʃl/", example: "This is a crucial moment."},
    {en: "culminate", cn: "v. 达到顶点；告终", phonetic: "/ˈkʌlmɪneɪt/", example: "The event culminated in a concert."},
    {en: "cumulative", cn: "adj. 累积的；渐增的", phonetic: "/ˈkjuːmjələtɪv/", example: "The cumulative effect is significant."},
    {en: "curb", cn: "v./n. 抑制；控制", phonetic: "/kɜːb/", example: "Curb your spending."},
    {en: "deduce", cn: "v. 推断；演绎", phonetic: "/dɪˈdjuːs/", example: "We can deduce the answer."},
    {en: "default", cn: "n. 违约；默认 v. 拖欠", phonetic: "/dɪˈfɔːlt/", example: "He defaulted on his loan."},
    {en: "defect", cn: "n. 缺陷；缺点", phonetic: "/ˈdiːfekt/", example: "The product has a defect."},
    {en: "deficient", cn: "adj. 不足的；有缺陷的", phonetic: "/dɪˈfɪʃnt/", example: "The diet is deficient in vitamins."},
    {en: "deliberate", cn: "adj. 故意的；深思熟虑的", phonetic: "/dɪˈlɪbərət/", example: "It was a deliberate choice."},
    {en: "delicate", cn: "adj. 精致的；微妙的", phonetic: "/ˈdelɪkət/", example: "This is a delicate situation."},
    {en: "demonstrate", cn: "v. 证明；演示", phonetic: "/ˈdemənstreɪt/", example: "Demonstrate your skills."},
    {en: "denounce", cn: "v. 谴责；告发", phonetic: "/dɪˈnaʊns/", example: "They denounced the policy."},
    {en: "depict", cn: "v. 描绘；描述", phonetic: "/dɪˈpɪkt/", example: "The painting depicts a scene."},
    {en: "deplete", cn: "v. 耗尽；使枯竭", phonetic: "/dɪˈpliːt/", example: "The river is depleted."},
    {en: "deploy", cn: "v. 部署；展开", phonetic: "/dɪˈplɔɪ/", example: "Deploy the troops."},
    {en: "deprive", cn: "v. 剥夺；使丧失", phonetic: "/dɪˈpraɪv/", example: "Don't deprive yourself of sleep."},
    {en: "derive", cn: "v. 源自；获得", phonetic: "/dɪˈraɪv/", example: "We derive pleasure from music."},
    {en: "descend", cn: "v. 下降；下来", phonetic: "/dɪˈsend/", example: "The plane descended."},
    {en: "designate", cn: "v. 指定；指派", phonetic: "/ˈdezɪɡneɪt/", example: "Designate a meeting place."},
    {en: "desperate", cn: "adj. 绝望的；拼命的", phonetic: "/ˈdespərət/", example: "He was desperate for help."},
    {en: "destiny", cn: "n. 命运；天命", phonetic: "/ˈdestəni/", example: "We control our own destiny."},
    {en: "detach", cn: "v. 分离；派遣", phonetic: "/dɪˈtætʃ/", example: "Detach the label."},
    {en: "deteriorate", cn: "v. 恶化；变坏", phonetic: "/dɪˈtɪəriəreɪt/", example: "His health deteriorated."},
    {en: "devastate", cn: "v. 毁灭；使震惊", phonetic: "/ˈdevəsteɪt/", example: "The war devastated the city."},
    {en: "deviate", cn: "v. 偏离；越轨", phonetic: "/ˈdiːvieɪt/", example: "Don't deviate from the plan."},
    {en: "diminish", cn: "v. 减少；降低", phonetic: "/dɪˈmɪnɪʃ/", example: "His influence diminished."},
    {en: "discern", cn: "v. 辨别；看出", phonetic: "/dɪˈsɜːn/", example: "I can discern a pattern."},
    {en: "disclose", cn: "v. 揭露；透露", phonetic: "/dɪsˈkləʊz/", example: "He disclosed the secret."},
    {en: "discrepancy", cn: "n. 差异；不一致", phonetic: "/dɪsˈkrepənsi/", example: "There's a discrepancy in the numbers."},
    {en: "discriminate", cn: "v. 歧视；辨别", phonetic: "/dɪˈskrɪmɪneɪt/", example: "It's wrong to discriminate."},
    {en: "disperse", cn: "v. 分散；驱散", phonetic: "/dɪˈspɜːs/", example: "The crowd dispersed."},
    {en: "displace", cn: "v. 取代；移置", phonetic: "/dɪsˈpleɪs/", example: "Technology displaced many jobs."},
    {en: "dispose", cn: "v. 处理；布置", phonetic: "/dɪˈspəʊz/", example: "Dispose of the trash."},
    {en: "dispute", cn: "n./v. 争论；争端", phonetic: "/dɪˈspjuːt/", example: "They had a dispute."},
    {en: "dissent", cn: "n./v. 异议；不同意", phonetic: "/dɪˈsent/", example: "Some voiced their dissent."},
    {en: "distort", cn: "v. 扭曲；歪曲", phonetic: "/dɪˈstɔːt/", example: "Don't distort the facts."},
    {en: "divert", cn: "v. 转移；使转向", phonetic: "/daɪˈvɜːt/", example: "Divert your attention."},
    {en: "dominate", cn: "v. 支配；占优势", phonetic: "/ˈdɒmɪneɪt/", example: "He dominates the conversation."},
    {en: "drastic", cn: "adj. 激烈的；极端的", phonetic: "/ˈdræstɪk/", example: "We need drastic measures."},
    {en: "duplicate", cn: "v. 复制 n. 副本", phonetic: "/ˈdjuːplɪkeɪt/", example: "Duplicate the document."},
    {en: "dwell", cn: "v. 居住；详述", phonetic: "/dwel/", example: "Don't dwell on the past."},
    {en: "eccentric", cn: "adj. 古怪的；反常的", phonetic: "/ɪkˈsentrɪk/", example: "He has eccentric habits."},
    {en: "elaborate", cn: "adj. 精心制作的 v. 详细说明", phonetic: "/ɪˈlæbərət/", example: "Elaborate on your plan."},
    {en: "elevate", cn: "v. 提高；举起", phonetic: "/ˈelɪveɪt/", example: "Elevate your standards."},
    {en: "elicit", cn: "v. 引出；诱出", phonetic: "/ɪˈlɪsɪt/", example: "The question elicited a response."},
    {en: "eligible", cn: "adj. 合格的；有资格的", phonetic: "/ˈelɪdʒəbl/", example: "Are you eligible for the job?"},
    {en: "eliminate", cn: "v. 消除；排除", phonetic: "/ɪˈlɪmɪneɪt/", example: "Eliminate the mistakes."},
    {en: "eloquent", cn: "adj. 雄辩的；有口才的", phonetic: "/ˈeləkwənt/", example: "She gave an eloquent speech."},
    {en: "embark", cn: "v. 着手；上船", phonetic: "/ɪmˈbɑːk/", example: "Embark on a new journey."},
    {en: "embody", cn: "v. 体现；使具体化", phonetic: "/ɪmˈbɒdi/", example: "He embodies the spirit of the team."},
    {en: "embrace", cn: "v. 拥抱；接受", phonetic: "/ɪmˈbreɪs/", example: "Embrace the change."},
    {en: "emerge", cn: "v. 出现；浮现", phonetic: "/ɪˈmɜːdʒ/", example: "New trends emerged."},
    {en: "emit", cn: "v. 发出；排放", phonetic: "/iˈmɪt/", example: "The factory emits smoke."},
    {en: "empirical", cn: "adj. 经验的；实证的", phonetic: "/ɪmˈpɪrɪkl/", example: "We need empirical evidence."},
    {en: "enforce", cn: "v. 执行；强制", phonetic: "/ɪnˈfɔːs/", example: "Enforce the rules."},
    {en: "engage", cn: "v. 从事；吸引", phonetic: "/ɪnˈɡeɪdʒ/", example: "Engage in conversation."},
    {en: "enhance", cn: "v. 提高；增强", phonetic: "/ɪnˈhɑːns/", example: "Enhance your skills."},
    {en: "enlighten", cn: "v. 启发；开导", phonetic: "/ɪnˈlaɪtn/", example: "Enlighten me on this topic."},
    {en: "enormous", cn: "adj. 巨大的；庞大的", phonetic: "/ɪˈnɔːməs/", example: "He has an enormous appetite."},
    {en: "ensure", cn: "v. 确保；保证", phonetic: "/ɪnˈʃʊə(r)/", example: "Ensure the quality."},
    {en: "entail", cn: "v. 需要；使必要", phonetic: "/ɪnˈteɪl/", example: "The job entails travel."},
    {en: "entity", cn: "n. 实体；存在", phonetic: "/ˈentəti/", example: "The company is a legal entity."},
    {en: "envisage", cn: "v. 设想；想象", phonetic: "/ɪnˈvɪzɪdʒ/", example: "I can't envisage the future."},
    {en: "equivalent", cn: "adj. 相等的 n. 等价物", phonetic: "/ɪˈkwɪvələnt/", example: "One dollar is equivalent to 7 yuan."},
    {en: "eradicate", cn: "v. 根除；消灭", phonetic: "/ɪˈrædɪkeɪt/", example: "We must eradicate poverty."},
    {en: "erode", cn: "v. 腐蚀；侵蚀", phonetic: "/ɪˈrəʊd/", example: "Water erodes rocks."},
    {en: "essential", cn: "adj. 必要的；本质的", phonetic: "/ɪˈsenʃl/", example: "Water is essential for life."},
    {en: "establish", cn: "v. 建立；确立", phonetic: "/ɪˈstæblɪʃ/", example: "Establish a routine."},
    {en: "esteem", cn: "n./v. 尊重；尊敬", phonetic: "/ɪˈstiːm/", example: "She is held in high esteem."},
    {en: "estimate", cn: "v./n. 估计；评价", phonetic: "/ˈestɪmeɪt/", example: "Estimate the cost."},
    {en: "evoke", cn: "v. 唤起；引起", phonetic: "/ɪˈvəʊk/", example: "The song evokes memories."},
    {en: "exaggerate", cn: "v. 夸大；夸张", phonetic: "/ɪɡˈzædʒəreɪt/", example: "Don't exaggerate."},
    {en: "exceed", cn: "v. 超过；超出", phonetic: "/ɪkˈsiːd/", example: "Sales exceeded expectations."},
    {en: "exemplify", cn: "v. 例证；是...的典范", phonetic: "/ɪɡˈzemplɪfaɪ/", example: "She exemplifies hard work."},
    {en: "exempt", cn: "adj. 被免除的 v. 豁免", phonetic: "/ɪɡˈzempt/", example: "He is exempt from taxes."},
    {en: "exert", cn: "v. 运用；施加", phonetic: "/ɪɡˈzɜːt/", example: "Exert your influence."},
    {en: "exhaust", cn: "v. 使筋疲力尽；耗尽", phonetic: "/ɪɡˈzɔːst/", example: "I'm exhausted."},
    {en: "exhibit", cn: "v. 展览；表现", phonetic: "/ɪɡˈzɪbɪt/", example: "The museum exhibits art."},
    {en: "explicit", cn: "adj. 明确的；清楚的", phonetic: "/ɪkˈsplɪsɪt/", example: "Give explicit instructions."}
];

// ============ 英语水平评估问卷 ============
const assessmentQuestions = [
    {
        question: "你目前的英语水平大概是？",
        options: [
            {text: "高考英语90分以下，基础比较薄弱", score: 1},
            {text: "高考英语90-120分，有一定基础", score: 2},
            {text: "高考英语120分以上，基础较好", score: 3},
            {text: "已经考过四级并通过", score: 4}
        ]
    },
    {
        question: "你平时记单词的情况如何？",
        options: [
            {text: "几乎不背单词，词汇量很小", score: 1},
            {text: "偶尔背，但坚持不下来", score: 2},
            {text: "有规律背单词，能坚持", score: 3},
            {text: "词汇量较大，背单词很快", score: 4}
        ]
    },
    {
        question: "你做英语听力时的状态是？",
        options: [
            {text: "基本听不懂，只能听懂个别单词", score: 1},
            {text: "能听懂大概意思，但细节抓不住", score: 2},
            {text: "大部分能听懂，偶尔有困难", score: 3},
            {text: "听力基本没问题，能抓细节", score: 4}
        ]
    },
    {
        question: "你做阅读理解时的情况是？",
        options: [
            {text: "生词太多，看不懂文章", score: 1},
            {text: "能看懂大意，但做题正确率低", score: 2},
            {text: "正确率还可以，但速度慢", score: 3},
            {text: "又快又准，阅读是强项", score: 4}
        ]
    },
    {
        question: "你写英语作文的情况是？",
        options: [
            {text: "基本写不出来，只会简单句", score: 1},
            {text: "能写但语法错误多，表达单一", score: 2},
            {text: "能写出结构完整的作文", score: 3},
            {text: "作文是强项，能运用高级表达", score: 4}
        ]
    },
    {
        question: "你做翻译题的情况是？",
        options: [
            {text: "完全不会翻译", score: 1},
            {text: "能翻译但中式英语严重", score: 2},
            {text: "翻译基本通顺，偶有错误", score: 3},
            {text: "翻译地道准确", score: 4}
        ]
    },
    {
        question: "你每天能投入多少时间学英语？",
        options: [
            {text: "不到30分钟", score: 1},
            {text: "30-60分钟", score: 2},
            {text: "1-2小时", score: 3},
            {text: "2小时以上", score: 4}
        ]
    },
    {
        question: "你备考的目标是？",
        options: [
            {text: "四级飘过（425分左右）", score: 1},
            {text: "四级高分（500+）", score: 2},
            {text: "六级通过（425+）", score: 3},
            {text: "六级高分（550+）或冲大英赛", score: 4}
        ]
    }
];

// ============ 四级真题（阅读+翻译+写作示例） ============
const cet4Questions = [
    {
        type: "reading",
        passage: "In recent years, more and more college students have chosen to study abroad. According to a recent survey, the number of Chinese students studying overseas has increased by 30% over the past five years. Many students believe that studying abroad can broaden their horizons and improve their language skills. However, some students find it difficult to adapt to the new environment due to cultural differences and language barriers.",
        question: "What is the main idea of this passage?",
        options: [
            "Studying abroad is too expensive.",
            "More Chinese students are choosing to study abroad.",
            "Students should not study abroad.",
            "Studying abroad has no benefits."
        ],
        answer: 1,
        analysis: "文章首句点明主旨：近年来越来越多的大学生选择出国留学。故选B。"
    },
    {
        type: "reading",
        passage: "In recent years, more and more college students have chosen to study abroad. According to a recent survey, the number of Chinese students studying overseas has increased by 30% over the past five years. Many students believe that studying abroad can broaden their horizons and improve their language skills. However, some students find it difficult to adapt to the new environment due to cultural differences and language barriers.",
        question: "According to the passage, what do many students think of studying abroad?",
        options: [
            "It is a waste of time.",
            "It can broaden their horizons.",
            "It is too difficult.",
            "It is not worth the money."
        ],
        answer: 1,
        analysis: "原文提到 studying abroad can broaden their horizons and improve their language skills，故选B。"
    },
    {
        type: "reading",
        passage: "The Internet has changed the way we communicate. With social media platforms, people can stay connected with friends and family regardless of distance. However, excessive use of social media can lead to addiction and negatively affect mental health. It is important to use social media in moderation.",
        question: "What does the author suggest about social media?",
        options: [
            "People should never use social media.",
            "Social media is only for young people.",
            "People should use social media in moderation.",
            "Social media has no negative effects."
        ],
        answer: 2,
        analysis: "最后一句明确指出 It is important to use social media in moderation，故选C。"
    },
    {
        type: "translation",
        passage: "中国是世界上最早使用纸币的国家。北宋时期，四川地区出现了世界上最早的纸币——交子。纸币的出现方便了商业交易，促进了经济发展。",
        question: "请将以上中文翻译成英文",
        options: [],
        answer: "China was the first country in the world to use paper money. During the Northern Song Dynasty, the world's earliest paper money, Jiaozi, appeared in Sichuan. The emergence of paper money facilitated commercial transactions and promoted economic development.",
        analysis: "翻译要点：①北宋时期 Northern Song Dynasty；②交子 Jiaozi（专有名词）；③促进经济发展 promote economic development。"
    },
    {
        type: "writing",
        passage: "Directions: For this part, you are allowed 30 minutes to write a short essay on the importance of reading. You should write at least 120 words but no more than 180 words.",
        question: "请根据题目要求写一篇作文",
        options: [],
        answer: "参考范文：\nThe Importance of Reading\n\nReading is of great importance in our daily life. Firstly, reading broadens our horizons and enriches our knowledge. Through reading, we can learn about different cultures, histories and ideas without traveling.\n\nSecondly, reading improves our language skills. By reading extensively, we can expand our vocabulary and learn various expressions, which are beneficial to our writing and speaking.\n\nFinally, reading is a good way to relax. After a long day of study or work, reading a good book can help us calm down and relieve stress.\n\nIn conclusion, reading is a valuable habit that everyone should develop. Let's make reading a part of our life.",
        analysis: "写作要点：①三段式结构（引入-主体-结论）；②使用连接词 firstly, secondly, finally；③结尾用 in conclusion 总结。"
    }
];

// ============ 六级真题（阅读+翻译+写作示例） ============
const cet6Questions = [
    {
        type: "reading",
        passage: "The concept of lifelong learning has gained increasing attention in recent years. With the rapid development of technology and the changing job market, individuals are expected to continuously update their knowledge and skills. Lifelong learning is no longer a choice but a necessity for personal and professional growth. Various online platforms and courses have made it easier for people to learn at their own pace, regardless of age or location.",
        question: "Why is lifelong learning considered a necessity according to the passage?",
        options: [
            "Because people have more free time now.",
            "Because technology and the job market are changing rapidly.",
            "Because traditional education is too expensive.",
            "Because online courses are free."
        ],
        answer: 1,
        analysis: "原文提到 With the rapid development of technology and the changing job market, lifelong learning is a necessity，故选B。"
    },
    {
        type: "reading",
        passage: "Urbanization has brought both benefits and challenges. On the one hand, cities offer more job opportunities, better education and healthcare facilities. On the other hand, rapid urbanization has led to problems such as traffic congestion, air pollution and housing shortages. To address these issues, sustainable urban development strategies are needed.",
        question: "What is one challenge mentioned in the passage caused by urbanization?",
        options: [
            "Lack of job opportunities",
            "Traffic congestion",
            "Poor healthcare",
            "Shortage of schools"
        ],
        answer: 1,
        analysis: "原文列举了 traffic congestion, air pollution and housing shortages，故选B。"
    },
    {
        type: "translation",
        passage: "中国茶文化源远流长，可以追溯到几千年前。茶不仅是一种饮品，更是一种文化和生活方式。品茶讲究色、香、味，注重意境和心境。如今，中国茶已走向世界，成为中华文化的重要名片。",
        question: "请将以上中文翻译成英文",
        options: [],
        answer: "Chinese tea culture has a long history that can be traced back thousands of years. Tea is not only a beverage, but also a culture and a way of life. Tea appreciation emphasizes color, aroma and taste, focusing on artistic conception and mental state. Today, Chinese tea has gone global and become an important calling card of Chinese culture.",
        analysis: "翻译要点：①源远流长 has a long history；②追溯到 be traced back to；③色、香、味 color, aroma and taste；④名片 calling card。"
    },
    {
        type: "writing",
        passage: "Directions: For this part, you are allowed 30 minutes to write an essay commenting on the saying \"The best preparation for tomorrow is doing your best today.\" You can cite examples to illustrate your point. You should write at least 150 words but no more than 200 words.",
        question: "请根据题目要求写一篇作文",
        options: [],
        answer: "参考范文：\nThe Best Preparation for Tomorrow\n\nThe saying \"The best preparation for tomorrow is doing your best today\" conveys a profound truth: the foundation of a bright future lies in our present efforts.\n\nFirstly, every achievement is built upon consistent daily efforts. For example, students who excel in exams are those who study diligently every day rather than cramming at the last minute. Similarly, successful professionals attribute their success to years of dedicated work.\n\nSecondly, focusing on today helps us avoid procrastination. Many people tend to delay important tasks, hoping to do them \"someday.\" However, \"someday\" never comes. By doing our best today, we ensure progress and build momentum for the future.\n\nIn conclusion, tomorrow belongs to those who work hard today. Let us seize the present moment and strive for excellence, for it is the most reliable path to a promising future.",
        analysis: "写作要点：①引用谚语并解释含义；②用例子支撑观点（学生+职场人士）；③反面论证（拖延的危害）；④总结升华。"
    }
];

// ============ 听力练习材料 ============
const listeningMaterials = [
    {
        title: "四级听力短篇新闻练习",
        audio: "news1",
        script: "A new study has found that regular exercise can improve memory and cognitive function. Researchers conducted experiments with 100 participants over a period of six months. The results showed that those who exercised at least three times a week performed significantly better on memory tests than those who did not exercise. The study suggests that even moderate exercise, such as walking for 30 minutes a day, can have a positive effect on brain health.",
        questions: [
            {
                question: "What did the new study find?",
                options: [
                    "Exercise can cause memory loss.",
                    "Regular exercise can improve memory.",
                    "Exercise has no effect on the brain.",
                    "Only vigorous exercise is beneficial."
                ],
                answer: 1
            },
            {
                question: "How long did the study last?",
                options: [
                    "Three months",
                    "Six months",
                    "One year",
                    "Two years"
                ],
                answer: 1
            },
            {
                question: "What kind of exercise is mentioned as beneficial?",
                options: [
                    "Running for an hour",
                    "Swimming twice a week",
                    "Walking for 30 minutes a day",
                    "Weight lifting every day"
                ],
                answer: 2
            }
        ]
    },
    {
        title: "六级听力长对话练习",
        audio: "conversation1",
        script: "W: Hi Tom, I heard you're planning to study abroad next year. Is that true?\nM: Yes, I've been thinking about it for a while. I've applied to several universities in the UK.\nW: That's exciting! What made you decide to study abroad?\nM: Well, I want to experience a different culture and improve my English. Also, the universities there offer excellent programs in my field.\nW: That makes sense. Have you considered the challenges? You know, being far from home and all.\nM: I have. I'm a bit nervous about adapting to a new environment, but I think it will be a valuable experience. I've been preparing by reading about British culture and practicing my English speaking skills.\nW: That's a good approach. Where will you stay?\nM: I'm planning to live in a student dormitory at first, and then maybe move to an apartment later.\nW: Sounds like a solid plan. I'm sure you'll do great!",
        questions: [
            {
                question: "Where does the man plan to study abroad?",
                options: [
                    "In the US",
                    "In Australia",
                    "In the UK",
                    "In Canada"
                ],
                answer: 2
            },
            {
                question: "Why does the man want to study abroad?",
                options: [
                    "To travel with friends",
                    "To experience a different culture and improve English",
                    "To find a job there",
                    "To escape from his family"
                ],
                answer: 1
            },
            {
                question: "What is the man's plan for accommodation?",
                options: [
                    "Rent an apartment immediately",
                    "Live with relatives",
                    "Stay in a student dormitory first",
                    "Live off campus"
                ],
                answer: 2
            }
        ]
    }
];

// ============ 小游戏用词汇（简单常用词）============
const gameWords = [
    {en: "apple", cn: "苹果"}, {en: "book", cn: "书"}, {en: "cat", cn: "猫"},
    {en: "dog", cn: "狗"}, {en: "water", cn: "水"}, {en: "food", cn: "食物"},
    {en: "happy", cn: "快乐的"}, {en: "sad", cn: "悲伤的"}, {en: "big", cn: "大的"},
    {en: "small", cn: "小的"}, {en: "hot", cn: "热的"}, {en: "cold", cn: "冷的"},
    {en: "run", cn: "跑"}, {en: "eat", cn: "吃"}, {en: "sleep", cn: "睡觉"},
    {en: "read", cn: "阅读"}, {en: "write", cn: "写"}, {en: "listen", cn: "听"},
    {en: "speak", cn: "说"}, {en: "love", cn: "爱"}, {en: "friend", cn: "朋友"},
    {en: "family", cn: "家庭"}, {en: "school", cn: "学校"}, {en: "teacher", cn: "老师"},
    {en: "student", cn: "学生"}, {en: "time", cn: "时间"}, {en: "money", cn: "钱"},
    {en: "work", cn: "工作"}, {en: "play", cn: "玩"}, {en: "music", cn: "音乐"},
    {en: "movie", cn: "电影"}, {en: "car", cn: "汽车"}, {en: "bus", cn: "公交车"}
];
